### ISSUE TITLE
insert a form instead to collect feedback

### ISSUE THREAD

**Issue by IAliceBobI** [The-OpenDAO/sos-market#2]
![](https://cdn.discordapp.com/attachments/932973691095113759/932973938315767868/Screenshot_2022-01-18_at_8.25.10_PM.png)

**Comment by Klongrich** [comment]
Hello! Running into "Unhandled Rejection (Error): Please add a Contract Address" When trying to build. 

How do you initialize the "public contracts: any = {};" in the src/services/BeproService.ts? 

Thank you in advance!
